name: 'test'
on:
  push:
  pull_request:
    paths: ['**.go', 'go.mod', '.github/workflows/*']

jobs:
  linux:
    name: 'test (linux)'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'WillAbides/setup-go-faster@v1'
        with: {go-version: '1.22'}
      - name: 'test (linux)'
        run: 'go test ./...'

  windows:
    name: 'test (windows)'
    runs-on: 'windows-latest'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'WillAbides/setup-go-faster@v1'
        with: {go-version: '1.22'}
      - name: 'test (windows)'
        run: 'go test ./...'

  macos:
    name: 'test (macos)'
    # TODO: if if I use macos-latest (14, on ARM) it will exit with "signal:
    # killed" after about ~3.5 minutes, on different tests.
    #
    # I don't know if this is a macOS 14 or ARM problem (my VM is an amd64 macOS
    # 13), but seems odd it would be a problem in elles(?)
    runs-on: 'macos-13'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'WillAbides/setup-go-faster@v1'
        with: {go-version: '1.22'}
      - name: 'test (macos)'
        run: 'go test ./...'

  freebsd:
    name: 'test (freebsd)'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
      - name: 'test (freebsd)'
        id:   'freebsd'
        uses: 'vmactions/freebsd-vm@v1'
        with:
          prepare: |
            pkg install -y go122
            pw user add -n action -m
          run: |
            echo 'XXXXXX'
            go version
            su action -c 'go122 test ./...'

  openbsd:
    name: 'test (openbsd)'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
      - name: 'test (openbsd)'
        id:   'openbsd'
        uses: 'vmactions/openbsd-vm@v1'
        with:
          prepare: |
            useradd -mG wheel action
            pkg_add go
          run: |
            echo 'XXXXXX'
            go version
            su action -c 'go test ./...'

  netbsd:
    name: 'test (netbsd)'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
      - name: 'test (netbsd)'
        id:   'netbsd'
        uses: 'vmactions/netbsd-vm@v1'
        with:
          prepare: |
            useradd -mG wheel action
            pkg_add go122
          run: |
            echo 'XXXXXX'
            /usr/pkg/bin/go122 version
            su action -c '/usr/pkg/bin/go122 test ./...'

  illumos:
    name: 'test (illumos)'
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v4'
    - name: 'test (illumos)'
      id:   'illumos'
      uses: 'vmactions/omnios-vm@v1'
      with:
        prepare: |
          useradd action
          pkg install go-122
        run: |
          echo 'XXXXXX'
          export GOCACHE=/tmp/go-cache
          export GOPATH=/tmp/go-path
          go version
          su action -c 'go test ./...'
